// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/peya/src/domain/repos"
	"github.com/peya/src/infra/postgres"
	"github.com/peya/src/usecases"
)

// Injectors from wire.go:

func InitializeInjector() *Injector {
	healthCheckDBRepo := ProvideHealthCheckDBRepo()
	healthCheckUsecaseImpl := ProvideHealthCheckUsecaseImpl(healthCheckDBRepo)
	injector := &Injector{
		HealthCheckUsecase: healthCheckUsecaseImpl,
	}
	return injector
}

// wire.go:

var Set = wire.NewSet(
	ProvideHealthCheckUsecaseImpl,
	ProvideHealthCheckDBRepo, wire.Bind(new(repos.HealthCheckRepo), new(*infra.HealthCheckDBRepo)), wire.Bind(new(usecases.HealthCheckUsecase), new(*usecases.HealthCheckUsecaseImpl)), wire.Struct(new(Injector), "*"),
)

type Injector struct {
	HealthCheckUsecase usecases.HealthCheckUsecase
}
